"""Shared constants for LSM Phase 1 fingerprint pipeline."""

N_LEFT_HAND = 21 * 2   # 42
N_RIGHT_HAND = 21 * 2  # 42
N_POSE = 17 * 3        # 51
FEATURE_DIM = N_LEFT_HAND + N_RIGHT_HAND + N_POSE  # 135
N_FRAMES = 85
FINGERPRINT_DIM = FEATURE_DIM * 6  # 810

POSE_OFFSET = N_LEFT_HAND + N_RIGHT_HAND  # 84
LEFT_SHOULDER_IDX = 11
RIGHT_SHOULDER_IDX = 12
VISIBILITY_THRESHOLD = 0.1
VISIBILITY_BIN_THRESHOLD = 0.5
MIN_VALID_FRAMES = 10

TOP_K_FILTER = 20
TOP_K_DTW = 5
CONFIDENCE_THR = 0.15
DTW_RADIUS = 10

BIN_MAGIC = 0x4C534D46  # "LSMF"
BIN_VERSION = 1
BIN_HEADER_SIZE = 64
